### ISSUE TITLE
It would be better to have list of organizations and tech stack to select from.

### ISSUE THREAD

**Issue by tushar5526** [Sparsh1212/gsocanalyzer#1]
Like a list on the right, containing all the organizations so far accepted and on the left tech stacks, like python, javascript, opengl etc.

**Comment by Sparsh1212** [comment]
@rishabhd786 can you scrape data in a manner such that I have separate json files which have a respective list.. For ex: one json file containing the list of all orgs, another json file containing all the tech stack from 2009-2019?
