### ISSUE TITLE
Add support for 2020 organisations

### ISSUE THREAD

**Issue by priyanshuone6** [Sparsh1212/gsocanalyzer#2]
Could you please update the repository and add support for the organizations for 2020

**Comment by Sparsh1212** [comment]
@priyanshuone6 Will be updated soon. Thank you for your interest.

**Comment by priyanshuone6** [comment]
Thanks a lot!

**Comment by priyanshuone6** [comment]
Hey, could you please tell me how to scrape the organization's data and what tool you used to scrape them so that I can add make a PR for updating the repo.

**Comment by Sparsh1212** [comment]
@priyanshuone6 please check the scrape.py file in the repo, you will get the idea about it.
