### ISSUE TITLE
Remove horizontal padding in mobile view

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#20]
There is some extra horizontal padding in the mobile view. That should be removed.

<img width="350" alt="Screenshot 2021-10-01 at 7 03 56 PM" src="https://user-images.githubusercontent.com/55937724/135628861-65b5d064-bb61-4df8-8e07-1fa3c4fd7dfb.png">

**Comment by wsameer** [comment]
@Sparsh1212 I would like to work on this

**Comment by Sparsh1212** [comment]
> @Sparsh1212 I would like to work on this

Thanks, @wsameer. Assigning this to you!

**Comment by joshi-kaushal** [comment]
Can I work on this?

**Comment by wsameer** [comment]
> > @Sparsh1212 I would like to work on this
> 
> Thanks, @wsameer. Assigning this to you!

Thank you

**Comment by Sparsh1212** [comment]
> Can I work on this?

@joshi-kaushal Thanks for showing interest! This has already been taken! Feel free to work on any other issue.
