### ISSUE TITLE
Add search suggestions for search by "Tech Stack"

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#21]
We want to integrate search suggestions when performing a search by "Tech Stack".
This will involve scraping a JSON list of all the tech stacks of GSoC projects and then the data has to be integrated into the search field of "Tech Stack"

**Comment by dolamanee6122** [comment]
Hey @Sparsh1212 , can you assign this issue to me.

**Comment by Sparsh1212** [comment]
> Hey @Sparsh1212 , can you assign this issue to me.

Apologies! @dolamanee6122, #27 fixed all 4 issues in one go, so this issue is no longer relevant.
