### ISSUE TITLE
Add 2021 data

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#22]
We want to update the tool by adding the 2021 GSoC data. This will involve scraping the data and adding it to the JSON file and then updating it on the frontend

**Comment by priyanshuone6** [comment]
We should wait till google archives 2021 as the script is made to scrape data from the archived website

**Comment by Sparsh1212** [comment]
@priyanshuone6 Yup, you are right. Just wanted to create a tracker issue for that!
Feel free to take upon this when 2021 data is added to the archive.

**Comment by Raeskaa** [comment]
Hi
I'd like to work on this issue!

**Comment by letsintegreat** [comment]
We can get organization data for the year 2021 now, as mentioned [here](https://api.gsocorganizations.dev/). So, I'd like to work on this issue and update the data for 2021.
