### ISSUE TITLE
Add search suggestions for search by "Category"

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#24]
We want to integrate search suggestions when performing a search by "Category".
This will involve scraping a JSON list of all the categories of GSoC projects and then the data has to be integrated into the search field of "Category"

**Comment by SuyashSonawane** [comment]
Hi @Sparsh1212 I would love to work on this issue

**Comment by Sparsh1212** [comment]
> Hi @Sparsh1212 I would love to work on this issue

All yours!
