### ISSUE TITLE
Rectify the alignment of searchbar and search button

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#3]
The alignment of the **search bar** and **search button** is not proper. this becomes more visible in the mobile view.

![image](https://user-images.githubusercontent.com/55937724/95001703-23709900-05ea-11eb-8602-fb1ee40a39bc.png)

**Comment by ReazerDev** [comment]
I'll look into this :)

**Comment by Yassine-Latreche** [comment]
Can you assign it to me please ?

**Comment by Ayush-Khandelwal-007** [comment]
please assign it to me.

**Comment by ReazerDev** [comment]
![image](https://user-images.githubusercontent.com/36013882/95003342-b277b400-05de-11eb-90b0-62612f1311c6.png)
Hi, btw. could you please do this :)^^
