### ISSUE TITLE
Refactor footer code to a separate component

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#33]
The footer code currently is a part of the homepage. It should be refactored into a separate `Footer` component.

**Comment by Marob-nod** [comment]
Hello, 
Can you assign me on this please ?

**Comment by Vishu-01** [comment]
Hello I am ready to take this issue if @Marob-nod is busy

**Comment by letsintegreat** [comment]
I'd like to work on this issue.
