### ISSUE TITLE
Redesign Homepage to show overall GSoC stats

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#34]
The current homepage shows no stats at all. It is much simple. It should be redesigned to render overall GSoC stats.

**Comment by Raeskaa** [comment]
Hi 
I'd like to work on this!
Can you please elaborate on what you want the homepage to be like

**Comment by riyajha2305** [comment]
Can u elaborate if u need a dynamic or a static display of GSoC Stats?

**Comment by Sparsh1212** [comment]
Hi @riyajha2305 I am planning to go with static data as per now. Later we might make it dynamic.
Also, I am not sure of the design as of now. So feel free to propose a design of your choice, we'll review it. Since, this issue will involve designing as well as coding, so decent number of points will be awarded to you. Let me know if you are excited to work on this.

**Comment by riyajha2305** [comment]
ok then I would want to go with this project. Can I be assigned this issue?

**Comment by Sparsh1212** [comment]
@riyajha2305 Let me know when you are done with the design part. We can then have a review session on discord.

**Comment by riyajha2305** [comment]
Will a figma design do?

**Comment by Sparsh1212** [comment]
> Will a figma design do?

Yup, will work great!

**Comment by Sparsh1212** [comment]
@riyajha2305 Please let me know the status update on this.

**Comment by aritroCoder** [comment]
Please assign the issue to me I will work on it
