### ISSUE TITLE
Change cursor style when hovering on "Visit Official Page"

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#35]

**Comment by Marob-nod** [comment]
hello ! Can you assign it to me please ?

**Comment by Marob-nod** [comment]
Well, somehone has already done a pull request

**Comment by Raeskaa** [comment]
Hi
I'd like to work on this

**Comment by Sparsh1212** [comment]
Assigning this to you @Raeskaa. Its all yours.

**Comment by riyajha2305** [comment]
Can I have this issue assigned?

**Comment by Sparsh1212** [comment]
@Raeskaa Are you working on this?

**Comment by Soumadipdas18** [comment]
Hello, can I solve it?

**Comment by Sparsh1212** [comment]
> Hello, can I solve it?

We will wait till tomorrow for @Raeskaa's confirmation. If he is not working on this, I'll assign this to you.

**Comment by chandrashekar27** [comment]
If no one else is working on this, can I be assigned to this issue?
