### ISSUE TITLE
Introduce Bookmarking orgs feature

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#36]
A Bookmark an org feature is to be added to all the cards, also a view bookmarks page should also be added.

**Comment by Komachian** [comment]
Hello! Wouldn't adding a bookmark feature require login functionality?

**Comment by Sparsh1212** [comment]
Hi @Komachian Nice thought. It could be implemented by maintating a database and introducing login functionality. However, we want to make it extremely easy for users to use this tool. So we basically want no authentication in this tool.

The way we can implement it withouth using auth is through local storage. I am thinking we can store a list of ids of bookmarked projects and can then render that.

**Comment by Komachian** [comment]
Oh. I would like to have a go at it then!

**Comment by Sparsh1212** [comment]
> Oh. I would like to have a go at it then!

Green light from my side 🟩
