### ISSUE TITLE
Clicking on Header ("GSoC Analyzer") should render launch page

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#37]

**Comment by varunxcode** [comment]
I can do it. Pls assign it to me.

**Comment by chandrashekar27** [comment]
Hi, can you assign it to me please?

**Comment by Sparsh1212** [comment]
@chandrashekar27 Since, @varunxcode approached first for this issue, so I will first wait to get his confirmation on his willingness to work on this issue. If he doesn't respond in some time, I will assign this to you.
@varunxcode Can you please confirm if you are up for working on this issue?

**Comment by varunxcode** [comment]
Yes i'm up for working on it #37.

**Comment by Sparsh1212** [comment]
Thanks for the confirmation @varunxcode. The issue is all yours :)

**Comment by Sparsh1212** [comment]
@varunxcode Can you please let us know the status of your PR? Let me know if you need any guidance.

**Comment by varunxcode** [comment]
i have pulled the request. what should i do now ?

**Comment by varunxcode** [comment]
I have done PR. Can you please tell me what to do next?

**Comment by Sparsh1212** [comment]
@varunxcode I have left some comments on your PR. Please take a look at them.

**Comment by Sparsh1212** [comment]
@chandrashekar27 Are you willing to work on this issue? Its currently not assigned to anyone.

**Comment by varunxcode** [comment]
I will be back soon after gaining enough knowledge.

**Comment by chandrashekar27** [comment]
> @chandrashekar27 Are you willing to work on this issue? Its currently not assigned to anyone.

Yes. I've started working on it.

**Comment by Raeskaa** [comment]
Hi,
I'd like to work on this issue!

**Comment by achintya7567** [comment]
Hi, can I work on this issue?

**Comment by Sparsh1212** [comment]
@varunxcode You can work on the learning part. Once done with that, let me know i'll assign you a new issue.
@Raeskaa Thanks for showing interest but @chandrashekar27 has approached before so this has been assigned to him. Feel free to work on any other issue which is not assigned to anyone else.

**Comment by chandrashekar27** [comment]
Hi @Sparsh1212. I was working on this issue and had a query regarding how the home page should look when we click the heading.
Initial serach
![image](https://user-images.githubusercontent.com/45785721/144604153-1ec43acd-29a5-4d1d-8f90-000c261ef92e.png)
After clicking heading
![image](https://user-images.githubusercontent.com/45785721/144604200-7d26494b-39c0-4787-b3e2-dea673c460a7.png)

Right now, this is what happens when I click the heading. Notice that the search bar still has the previous search in it.
Is that fine or should I try to remove that as well??

**Comment by riyajha2305** [comment]
Can I be assigned this issue?

**Comment by Sparsh1212** [comment]
> Hi @Sparsh1212. I was working on this issue and had a query regarding how the home page should look when we click the heading. Initial search ![image](https://user-images.githubusercontent.com/45785721/144604153-1ec43acd-29a5-4d1d-8f90-000c261ef92e.png) After clicking heading ![image](https://user-images.githubusercontent.com/45785721/144604200-7d26494b-39c0-4787-b3e2-dea673c460a7.png)
> 
> Right now, this is what happens when I click the heading. Notice that the search bar still has the previous search in it. Is that fine or should I try to remove that as well??

Please make sure the search bar is also reset to none.
