### ISSUE TITLE
Unused import statements in OrganisationCard.js

### ISSUE THREAD

**Issue by letsintegreat** [Sparsh1212/gsocanalyzer#43]
`Button`, `Label`, `FontAwesomeIcon`, and `faBolt` were imported in [OrganisationCard.js](https://github.com/Sparsh1212/gsocanalyzer/blob/master/src/components/OrganisationCard.js) but were never used. These redundant imports should be removed.

**Comment by ShivaRapolu01** [comment]
Can you please assign this issue to me
