### ISSUE TITLE
Introduce Searching with multiple tags Feature

### ISSUE THREAD

**Issue by chandrashekar27** [Sparsh1212/gsocanalyzer#49]
Add a new feature that allows the user to search for projects using multiple 'tags'. This would help the user get more specific information and get it faster.

For Ex: Search for projects that use both Python AND Javascript

This could be achieved by modifying the search bar to hold multiple 'tags' simultaneously (any other working method is also fine)

Note: We can also allow the user to choose multiple search 'tags' of different types (Tech Stack, Org Name, etc.) simultaneously.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.
