### ISSUE TITLE
Fix height of graph in mobile view

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#5]
The graph takes much less height in the mobile view, making the visibility of the contents poor.
Increase the height that the graph takes in the mobile view.

![image](https://user-images.githubusercontent.com/55937724/95007701-4cb41800-0630-11eb-9c8d-4c0ff4a7fb82.png)

**Comment by himankpathak** [comment]
Hey @Sparsh1212, is this issue up for taking?
I would like to work on this.

**Comment by Sparsh1212** [comment]
@himankpathak Yes. I am assigning it to you.

**Comment by amaanweb** [comment]
Could you please assign it to me.
