### ISSUE TITLE
Fix the footer to keep it consistent

### ISSUE THREAD

**Issue by Sparsh1212** [Sparsh1212/gsocanalyzer#56]
Currently, on the landing page, the footer is inconsistent. It keeps on shifting downwards as more and more text gets rendered on the screen. We want its position to be fixed just like a usual footer.

**Comment by chandrashekar27** [comment]
I want to work on this.

**Comment by chandrashekar27** [comment]
Hey @Sparsh1212 , can you please clarify what you mean by consistent. Do you mean the footer should _always_ be at the bottom the page, even in the launch page?

**Comment by Sparsh1212** [comment]
> Hey @Sparsh1212 , can you please clarify what you mean by consistent. Do you mean the footer should _always_ be at the bottom the page, even in the launch page?

Please see the video demonstration here. You can observe that the footer keeps on going downwards as more and more text appears. We should make its position permanent.

https://user-images.githubusercontent.com/55937724/145339370-1411888f-97e5-4151-afc7-6828ace3fe5d.mov

**Comment by Sparsh1212** [comment]
> i would also like to work on this 😃

@iamrahulrnair Apologies but @chandrashekar27 has already approached first to work on this issue and only one person can be assigned at a time. So please look for any other unassigned issue.

**Comment by iamrahulrnair** [comment]
sure thanks 😉

**Comment by chandrashekar27** [comment]
> > Hey @Sparsh1212 , can you please clarify what you mean by consistent. Do you mean the footer should _always_ be at the bottom the page, even in the launch page?
> 
> Please see the video demonstration here. You can observe that the footer keeps on going downwards as more and more text appears. We should make its position permanent.
> 
>  Screen.Recording.2021-12-09.at.10.49.45.AM.mov

Alright, I got what you meant. Will work on it

**Comment by Sparsh1212** [comment]
@chandrashekar27 Can you please work on this on priority. We need to fix this ASAP!

**Comment by chandrashekar27** [comment]
> @chandrashekar27 Can you please work on this on priority. We need to fix this ASAP!

@Sparsh1212 I've been trying... but I keep getting stuck. Because the text renders with a time delay, the size of the `animatedText` div keeps changing. Can you suggest a method to keep it constant from the start?

**Comment by Sparsh1212** [comment]
> > @chandrashekar27 Can you please work on this on priority. We need to fix this ASAP!
> 
> @Sparsh1212 I've been trying... but I keep getting stuck. Because the text renders with a time delay, the size of the `animatedText` div keeps changing. Can you suggest a method to keep it constant from the start?

Hmm sounds interesting!
Maybe we have to hardcode the min. distance of footer from the top. This can help in keeping it consistent. Also please make sure that you hardcode different values of min-height in Desktop and mobile view. Feel free to discuss a better solution if you find any

**Comment by Sparsh1212** [comment]
> > > @chandrashekar27 Can you please work on this on priority. We need to fix this ASAP!
> > 
> > 
> > @Sparsh1212 I've been trying... but I keep getting stuck. Because the text renders with a time delay, the size of the `animatedText` div keeps changing. Can you suggest a method to keep it constant from the start?
> 
> 
@chandrashekar27 
Hmm sounds interesting! Maybe we have to hardcode the min. distance of footer from the top. This can help in keeping it consistent. Also please make sure that you hardcode different values of min-height in Desktop and mobile view. Feel free to discuss a better solution if you find any

**Comment by chandrashekar27** [comment]
Hey @Sparsh1212, 
I thought we could try to solve this by initially setting a minimum height for the `animatedText` div.  I think this makes the footer component stay in a consistent position. Please take a look and tell if any changes are required :)
