### ISSUE TITLE
Duplicate entries for organizations.

### ISSUE THREAD

**Issue by letsintegreat** [Sparsh1212/gsocanalyzer#66]
# Description
As some organizations used different names while participating in GSoC, there are multiple entries for them in [finalData.json](https://github.com/Sparsh1212/gsocanalyzer/blob/master/src/data/finalData.json).

Like:

> Stony Brook University Biomedical Informatics
Stony Brook University, Biomedical Informatics

> GFOSS - Open Technology Alliance
GFOSS - Open Technologies Alliance
Open Technologies Aliance - GFOSS
Open Technologies Alliance - GFOSS

> FOSSology
FOSSology Project

However, the data provided [here](https://api.gsocorganizations.dev/organizations.json) by Google, contains one single entry for each organization. So we can recompile the entire finalData.json from the given link to remove all the discrepancies at once.

**Comment by ShivaRapolu01** [comment]
If this issue is not assigned , I can work on this

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by ShivaRapolu01** [comment]
Yeah @letsintegreat  , you pointed out this issue so you must go ahead 👍

**Comment by Sparsh1212** [comment]
@ShivaRapolu01 Thanks for showing interest in the issue. But since @letsintegreat pointed this out and he is willing to fix that, we have to assign him.
Feel free to comment on any unassigned issue.
