### ISSUE TITLE
Introduce sorting with different parameters

### ISSUE THREAD

**Issue by chandrashekar27** [Sparsh1212/gsocanalyzer#70]
# Description
Create feature to sort results with different parameters like
- Total number of times in GSoC
- Avg number of projects per year
- Avg number of projects in recent years

**Comment by Komachian** [comment]
Hey, I'd like to work on this one

**Comment by Sparsh1212** [comment]
This issue could be made more general by introducing sorting with different parameters. As a start, we can begin with the total no. of times in GSoC and the average number of projects per year. Please edit the issue title and description as per this comment.

**Comment by Sparsh1212** [comment]
@Komachian Please let me know if you would like to work on this issue based on its updated description.

**Comment by Komachian** [comment]
Hmm. Here's what I understood, we'll have an option (a drop-down menu maybe) from where the user could choose a particular parameter to sort the results displayed instead of having to stick with the default parameter at present. Am I correct?

**Comment by Sparsh1212** [comment]
> Hmm. Here's what I understood, we'll have an option (a drop-down menu maybe) from where the user could choose a particular parameter to sort the results displayed instead of having to stick with the default parameter at present. Am I correct?

Yes exactly, you got it right.
